image: node:16.8.0

stages:
  # - publish
  - build_stage
  - pm2_stage
  # - deploy_stage

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

.before_script_template:
  before_script:
    - echo "====== Pre script ======"
    # - printenv
    - echo "$CI_COMMIT_BRANCH" && echo "$CI_PIPELINE_SOURCE" && echo "$CI_COMMIT_TAG"
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -t rsa 64.227.1.160 > ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 644 ~/.ssh/known_hosts

# .base-rules:
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "develop"'
#       when: always
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#       when: never
#     - if: $CI_COMMIT_TAG
#       when: never

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  policy: pull-push
  paths:
    - node_modules/
    - package-lock.json

# publish:
#   image: docker:latest
#   stage: publish
#   services:
#     - docker:dind
#   rules: 
#     - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main" ' 
#       when: always
#     - if: '$CI_COMMIT_BRANCH != "develop" || $CI_COMMIT_BRANCH != "main" ' 
#       when: never
#     - when: on_success
#   script:
#     - docker build -t $TAG_COMMIT -t $TAG_LATEST .
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#     - docker push $TAG_COMMIT
#     - docker push $TAG_LATEST
#   tags:
#     - server_runner



# deploy:
#   image: alpine:latest
#   stage: build_stage
#   rules: 
#     - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main" ' 
#       when: always
#     - if: '$CI_COMMIT_BRANCH != "develop" || $CI_COMMIT_BRANCH != "main" ' 
#       when: never
#     - when: on_success
#   tags:
#     - server_runner
#   script:
#     - chmod og= $SSH_PRIVATE_KEY
#     - apk update && apk add openssh-client
#     - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#     - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker ls -a"
#     - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
#     - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f myhappywallet || true"
#     - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 80:80 --name myhappywallet $TAG_COMMIT"

build:
  stage: build_stage
  extends: .before_script_template
  rules: 
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main" ' 
      when: always
    - if: '$CI_COMMIT_BRANCH != "develop" || $CI_COMMIT_BRANCH != "main" ' 
      when: never
    - when: on_success
  script:
    - echo "====== Deploy to production server ======"
    - echo "Test ssh connection"
    # - ssh -o StrictHostKeyChecking=no -T "$SERVER_USER@$SERVER_IP"
    # Delploy
    - echo "Setup tagget server directories"
    - node --version
    - npm i
    - npm run build
  cache:
    <<: *global_cache
    policy: push
  tags:
    - server_runner

deploy:
  image: keymetrics/pm2:6
  stage: pm2_stage
  rules: 
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main" ' 
      when: always
    - if: '$CI_COMMIT_BRANCH != "develop" || $CI_COMMIT_BRANCH != "main" ' 
      when: never
    - when: on_success
  script:
    - echo "====== pm2 stage to server ======"
    # - ssh -o StrictHostKeyChecking=no -T "$SERVER_USER@$SERVER_IP"
    # Delploy
    - echo "Setup tagget server directories"
    - ls -a
    - pm2 start ecosystem.config.js --only myhappywallet
  cache:
    <<: *global_cache
    policy: push
  tags:
    - server_runner

# deploy:
#   image: keymetrics/pm2:6
#   stage: deploy_stage
#   extends: .before_script_template
#   rules: 
#     - if: '$CI_COMMIT_BRANCH == "main"'
#       when: always
#     - if: '$CI_COMMIT_BRANCH == "develop"'
#       when: never
#     - when: on_success
#   script:
#       # Delploy
#     - echo "====== Deploy to production server ======"
#     - echo "Setup tagget server directories"
#     # - pm2 deploy ecosystem.config.js production setup 2>&1 || true
#     # - echo "make deploy"
#     # - pm2 deploy ecosystem.config.js production
#     # - "pm2 startOrGracefulReload ecosystem.config.js --env production && pm2 save"
#     - pm2 start ecosystem.config.js --only myhappywallet
#   cache:
#     <<: *global_cache
#     policy: pull
#   tags:
#     - server_runner
